### ISSUE TITLE
Website certificate problem

### ISSUE THREAD

**Issue by ThatDaleMiller** [abella-prover/abella-prover.org#15]
When visiting abella-prover.org today I got the following error message.

`Your connection is not private: net::ERR_CERT_DATE_INVALID`

Does this mean we need a new certificate?

**Comment by chaudhuri** [comment]
Something went wrong with the SSL certificate renewal which is supposed to happen automatically. I've filed a support ticket with the hosting provider. Hopefully it's resolved on a few minutes.

**Comment by ThatDaleMiller** [comment]
It seems fixed now.  Thanks.
